In [162]:
import xml.etree.ElementTree as ET
import pandas as pd
import re
pd.set_option('display.max_columns', 500)

In [59]:
JELtree = ET.parse('classificationTree.xml')

In [70]:
root = JELtree.getroot()

In [76]:
code_list = []
for i in root.findall('./classification/classification/classification/code'):
    code_list.append(i.text)
code_text = []
for i in root.findall('./classification/classification/classification/description'):
    code_text.append(i.text)
for i,text in enumerate(code_text):
    code_text[i] = re.sub(' &bull;', ';', text)

In [103]:
df_lv3 = pd.DataFrame({'Code': code_list, 'Description': code_text})

In [138]:
dict_lv3 = {}
for i in range(len(df_lv3)):
    dict_lv3[df_lv3.iloc[i, 1].upper()] = df_lv3.iloc[i, 0]

In [105]:
code_list = []
for i in root.findall('./classification/classification/code'):
    code_list.append(i.text)
code_text = []
for i in root.findall('./classification/classification/description'):
    code_text.append(i.text)
for i,text in enumerate(code_text):
    code_text[i] = re.sub(' &bull;', ';', text)

In [106]:
df_lv2 = pd.DataFrame({'Code': code_list, 'Description': code_text})

In [139]:
dict_lv2 = {}
for i in range(len(df_lv2)):
    dict_lv2[df_lv2.iloc[i, 1].upper()] = df_lv2.iloc[i, 0]

In [108]:
code_list = []
for i in root.findall('./classification/code'):
    code_list.append(i.text)
code_text = []
for i in root.findall('./classification/description'):
    code_text.append(i.text)
for i,text in enumerate(code_text):
    code_text[i] = re.sub(' &bull;', ';', text)

In [109]:
df_lv1 = pd.DataFrame({'Code': code_list, 'Description': code_text})

In [140]:
dict_lv1 = {}
for i in range(len(df_lv1)):
    dict_lv1[df_lv1.iloc[i, 1].upper()] = df_lv1.iloc[i, 0]

In [123]:
tree = ET.parse('../../../JPE/JPE.xml')

In [124]:
root = tree.getroot()

In [125]:
# for tig in root.findall('./rec/header/controlInfo/artinfo/tig/atl'):
#     print(tig.tag, tig.text)

In [146]:
article_list = []
cls_list_agg = []
for i in root.findall('./rec/header/controlInfo/artinfo'):
    article = i.findall('tig/atl')
    article_list.append(article[0].text)
#     print(article[0].text)
#     print(' ')
    try:
        cls_list = [dict_lv3[j.text.upper()] for j in i.findall('su')]
        cls_list_agg.append(cls_list)
    except KeyError:
        cls_list = []
        cls_list_agg.append(cls_list)
        continue

In [148]:
cls_list_agg

[['D02', 'D71', 'D72'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D74', 'F51', 'O17'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['L26', 'O14', 'O31'],
 ['A14'],
 [],
 [],
 [],
 [],
 ['J12', 'J13', 'J22', 'K36'],
 ['A11'],
 ['D82', 'D86'],
 [],
 [],
 [],
 ['D12', 'D81'],
 [],
 [],
 ['C72', 'D64'],
 [],
 [],
 [],
 [],
 [],
 ['D84', 'F31', 'F33', 'F41'],
 [],
 [],
 [],
 ['E24', 'J64', 'K42'],
 [],
 ['L66'],
 ['C51', 'I26', 'J24', 'J31'],
 [],
 ['R11', 'R58'],
 [],
 ['I12'],
 ['G12'],
 ['D25', 'G12', 'G31'],
 [],
 [],
 [],
 [],
 [],
 ['K42', 'L82'],
 [],
 [],
 ['F31', 'F41'],
 ['L82', 'L86', 'O34'],
 [],
 ['D72'],
 [],
 ['E32', 'F32', 'F41'],
 [],
 [],
 [],
 [],
 ['D21', 'D86'],
 [],
 [],
 ['E32', 'F41'],
 [],
 [],
 [],
 ['A14'],
 ['A14'],
 [],
 [],
 ['D12', 'D84', 'E44', 'G01', 'G11', 'G14'],
 ['D81', 'G32', 'J23', 'L26', 'M13'],
 [],
 ['F43', 'O41'],
 [],
 [],
 ['Y20'],
 ['A14'],
 [],
 [],
 ['F12', 'J61', 'O32', 'R12', 'R32'],
 [],
 ['E52', 'E63', 'E62'],
 [],
 [],
 [],
 ['D82', 'G21', 'G32', 'M13'],
 ['G32', 'L85', 'R33'],
 [],
 [],
 ['C73'],
 [],
 ['A11'],
 ['A11', 'A14'],
 [],
 [],
 ['F31'],
 [],
 ['F31'],
 [],
 [],
 ['D64', 'D15', 'E62', 'H55'],
 ['G32', 'J23', 'L26', 'M13'],
 [],
 ['J12'],
 ['E24', 'E31', 'E52'],
 ['D64', 'H41', 'L31'],
 [],
 [],
 [],
 [],
 ['J31', 'J23', 'J24'],
 [],
 [],
 ['F14', 'F41', 'H11'],
 [],
 [],
 [],
 ['A14'],
 ['H26', 'K42'],
 ['J22', 'J24', 'J31'],
 [],
 [],
 [],
 ['A14'],
 [],
 ['D15', 'E62', 'O23', 'O41'],
 [],
 [],
 [],
 [],
 ['E52', 'E62'],
 [],
 ['D15', 'G12'],
 ['A14'],
 ['C61', 'C62', 'E51', 'E52'],
 [],
 ['E31', 'F13', 'F31', 'F33'],
 ['A14'],
 [],
 [],
 ['D12', 'D14', 'J12'],
 ['D12', 'J12', 'O12'],
 ['C62', 'E32', 'E52'],
 [],
 [],
 ['E31', 'O11'],
 ['E31', 'O11'],
 ['F31', 'F33', 'O19'],
 ['E32', 'H42', 'O41'],
 ['C63', 'D52', 'D81'],
 ['O41'],
 [],
 [],
 [],
 ['E41', 'E42', 'E52', 'E62', 'O41', 'O47'],
 [],
 [],
 [],
 [],
 [],
 ['O32', 'O34', 'O41'],
 ['O41', 'D33'],
 [],
 [],
 [],
 [],
 ['G11', 'G12'],
 ['C61', 'O41'],
 ['E58'],
 [],
 ['D12', 'D14', 'E32', 'G11', 'G12'],
 ['F33', 'F42', 'F36'],
 ['C63', 'D52', 'D81'],
 ['G12'],
 [],
 [],
 [],
 [],
 ['C51', 'D83', 'G12'],
 ['E52', 'E58'],
 ['G11', 'G12', 'G15'],
 [],
 [],
 [],
 [],
 [],
 ['D52', 'G22', 'I12'],
 [],
 ['G32', 'L25'],
 ['G12', 'G14'],
 [],
 [],
 ['D24', 'D82', 'D86', 'G32'],
 [],
 ['G32', 'G35', 'L25'],
 ['E31', 'E52', 'E62', 'F33'],
 [],
 [],
 ['D12', 'D81', 'D82', 'G22'],
 ['G12', 'G35'],
 [],
 ['D82'],
 ['D13', 'J22'],
 [],
 [],
 ['G32', 'K22'],
 ['I12', 'J14'],
 [],
 [],
 ['O11', 'O41'],
 ['D23', 'L83'],
 ['G31', 'G32'],
 ['D82'],
 ['C71', 'D71', 'D85'],
 [],
 [],
 ['G21', 'G33'],
 [],
 ['O33'],
 ['E24', 'E31', 'E32', 'E52'],
 [],
 [],
 [],
 ['A14'],
 ['C51', 'G12'],
 [],
 [],
 ['D12', 'I12'],
 [],
 [],
 [],
 ['G31', 'L11'],
 [],
 [],
 ['R11', 'R12'],
 ['D23', 'D83'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['C78', 'D83'],
 [],
 [],
 ['D15', 'I12'],
 ['F31'],
 ['D83', 'F31'],
 [],
 [],
 [],
 [],
 [],
 ['D71'],
 [],
 ['E31', 'E42', 'F31'],
 ['A14'],
 ['G12', 'G14'],
 [],
 ['E31'],
 ['L94', 'M12', 'L51'],
 [],
 ['J31'],
 ['J33', 'L83'],
 ['I21', 'M37'],
 [],
 [],
 ['D72', 'D74', 'O17'],
 [],
 ['Y20'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'F13', 'F51'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'H55', 'H75', 'H77', 'J32'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'F21', 'L11', 'L52', 'O14', 'O17', 'O19'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'J15', 'J61', 'K37'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['A11', 'B41', 'D72'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'E24', 'F21', 'F23', 'J51'],
 [],
 [],
 [],
 ['Y20'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D22', 'D24', 'D72', 'K42', 'L25', 'O14', 'O17'],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'D74', 'O17'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'E32', 'E62', 'O11', 'O17', 'O23'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'F31', 'L52', 'L62', 'O14', 'O25'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D02', 'D72', 'O11', 'O17', 'O43'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'D82', 'D83'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['H72', 'H75', 'J32', 'J45'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'O17'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'G11', 'H55'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'E44', 'E52', 'E58', 'G21'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'F14', 'H11', 'O17', 'O19'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'G01', 'G21'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'F55'],
 [],
 [],
 [],
 ['D72', 'H55', 'J12', 'J31'],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'K42'],
 [],
 ['C81', 'D72', 'O17'],
 [],
 ['D02', 'D72', 'D74'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'D83'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['G01', 'H72', 'H74', 'R11', 'R51'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D12', 'D22', 'D72', 'D83', 'L82'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Y20'],
 [],
 [],
 [],
 ['D72', 'L92', 'R41'],
 [],
 [],
 [],
 ['A14'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'O17'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Y20'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'E52', 'E58'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D72', 'F31', 'O17', 'O19'],
 [],
 [],
 [],
 [],
 ['D72', 'F13', 'F15'],
 [],
 [],
 ['D72', 'F53'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['D74', 'H56', 'O17'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['C63', 'D72'],
 [],
 [],
 ['Y20'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ...]

In [166]:
df_JPE = pd.DataFrame({'title': article_list, 'JEL': cls_list_agg})

In [167]:
df_JPE['JEL_len'] = df_JPE['JEL'].apply(len)

In [168]:
df_JPE = df_JPE[df_JPE['JEL_len']!=0]

In [170]:
df_JPE.drop(columns = 'JEL_len', inplace=True)

In [171]:
df_JPE

                                                   title                   JEL
0      Political Economics in the Journal of Politica...       [D02, D71, D72]
8      Terrain Ruggedness and Land Cover: Improved Da...       [D74, F51, O17]
15            Innovation Drivers in Developing Countries       [L26, O14, O31]
16     Episodes in the History of the Journal of Poli...                 [A14]
21     Child Custody and Family Labour Supply: Eviden...  [J12, J13, J22, K36]
...                                                  ...                   ...
22622  Introduction to Symposium on Hayek's The Road ...                 [Y20]
22623  How High Can Inflation Get during Hyperinflati...            [E31, E41]
22624  Erratum to 'The Monetary Dynamics in the Yugos...  [E31, E41, E51, E52]
22751       Christianity and economic problems. [Review]                 [A12]
22778               State universities and labor bureaus                 [J01]

[4766 rows x 2 columns]

In [156]:
df_text = pd.read_csv('../../../../TTIC31220/wos_econ_text_filtered.csv')

/Users/hesongrun/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (7,8,13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [158]:
df_text = df_text[df_text['source']=='JOURNAL OF POLITICAL ECONOMY']

In [160]:
df_JPE['title'] = df_JPE['title'].str.upper()
df_text['title'] = df_text['title'].str.upper()

In [182]:
df_JPE_JEL = pd.merge(df_text[['title', 'abstract']], df_JPE, on = 'title')

In [186]:
def get_first(x):
    return x[0][0]
df_JPE_JEL['JEL_first'] = df_JPE_JEL['JEL'].apply(get_first)

In [191]:
dict_lv1_inv = {}
for i in range(len(df_lv1)):
    dict_lv1_inv[df_lv1.iloc[i, 0]] = df_lv1.iloc[i, 1].upper()

In [194]:
def get_cls_text(x):
    return dict_lv1_inv[x]

In [196]:
df_JPE_JEL['Class'] = df_JPE_JEL['JEL_first'].apply(get_cls_text)

In [201]:
df_JPE_JEL.to_pickle('JPE_JEL.pkl')

In [204]:
df_JPE_JEL.groupby('Class').count()['abstract'].reset_index().sort_values(by='abstract')

                                                Class  abstract
3                                    ECONOMIC SYSTEMS         1
0   AGRICULTURAL AND NATURAL RESOURCE ECONOMICS; E...         2
15  URBAN, RURAL, REGIONAL, REAL ESTATE, AND TRANS...         5
5                      GENERAL ECONOMICS AND TEACHING         6
2   ECONOMIC DEVELOPMENT, INNOVATION, TECHNOLOGICA...         9
1   BUSINESS ADMINISTRATION AND BUSINESS ECONOMICS...        10
10                                  LAW AND ECONOMICS        13
14                                   PUBLIC ECONOMICS        15
6                      HEALTH, EDUCATION, AND WELFARE        18
12              MATHEMATICAL AND QUANTITATIVE METHODS        34
7                             INDUSTRIAL ORGANIZATION        36
8                             INTERNATIONAL ECONOMICS        37
4                                 FINANCIAL ECONOMICS        38
11              MACROECONOMICS AND MONETARY ECONOMICS        44
9                     LABOR AND DEMOGRAPHIC ECONOMICS        61
13                                     MICROECONOMICS       218

In [205]:
df_JPE_JEL.groupby('JEL_first').count()['abstract'].reset_index().sort_values(by='abstract')

   JEL_first  abstract
13         P         1
14         Q         2
15         R         5
0          A         6
12         O         9
11         M        10
9          K        13
6          H        15
7          I        18
1          C        34
10         L        36
4          F        37
5          G        38
3          E        44
8          J        61
2          D       218

In [211]:
df_new = df_text[['title', 'pubyear', 'pubmonth', 'pubday']]

In [213]:
df_JPE_JEL = pd.merge(df_JPE_JEL, df_new, on = 'title')

In [214]:
df_JPE_JEL.to_pickle('JPE_JEL.pkl')

In [218]:
df_JPE_JEL.groupby('pubyear').count()

         title  abstract  JEL  JEL_first  Class  pubmonth  pubday
pubyear
1992        14        14   14         14     14        14      14
1993        11        11   11         11     11        11      11
1994         9         9    9          9      9         9       9
1995        16        16   16         16     16        16      16
1996        19        19   19         19     19        19      19
1997        26        26   26         26     26        26      26
1998        23        23   23         23     23        23      23
1999        31        31   31         31     31        31      31
2000        27        27   27         27     27        27      27
2001        22        22   22         22     22        22      22
2002        26        26   26         26     26        26      26
2003        23        23   23         23     23        23      23
2004        31        31   31         31     31        31      31
2005        25        25   25         25     25        25      25
2006        21        21   21         21     21        21      21
2007        22        22   22         22     22        22      22
2008        13        13   13         13     13        13      13
2009        15        15   15         15     15        15      15
2010        17        17   17         17     17        17      17
2011        15        15   15         15     15        15      15
2012        10        10   10         10     10        10      10
2013        19        19   19         19     19        19      19
2014        19        19   19         19     19        19      19
2015        13        13   13         13     13        13      13
2016        16        16   16         16     16        16      16
2017        14        14   14         14     14        14      14
2018        29        29   29         29     29        29      29
2019        21        21   21         21     21        21      21